### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [noumar/iso639#10]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'test.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./iso639/iso639.py:247: DeprecationWarning: invalid escape sequence \[
  m = re.findall('\[([a-z]{3})\]', s)
```

**Comment by noumar** [comment]
Fixed by using raw string. Fix is on `main`.
