### ISSUE TITLE
Way to retrieve the language code given the language string?

### ISSUE THREAD

**Issue by philgooch** [noumar/iso639#5]
Hi there, thanks for creating this, it's a great resource.

A very simple use case I have is to return the ISO-639-1 and ISO-639-2 codes for a given long-form.

E.g calling a function with 'French' would return `('fr', 'fra')`.

Is this possible with your module?

**Comment by philgooch** [comment]
Sorry, stupid request! Functionality is there, I just missed it.

**Comment by noumar** [comment]
No worries. And thanks. It's nice to hear that someone else uses it 😄

As reference for others you can use `languages.get(name="French")`.
I will add an example to the Usage section.
